# Generated by Django 2.1.5 on 2021-06-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Field')),
                ('content', models.CharField(max_length=30)),
            ],
            bases=('blog.field',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Field')),
                ('content', models.CharField(max_length=30)),
            ],
            bases=('blog.field',),
        ),
        migrations.RemoveField(
            model_name='field',
            name='field_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='choices',
            field=models.ManyToManyField(to='blog.Choice'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
