# Generated by Django 2.1.5 on 2021-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210627_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.CharField(choices=[('item', 'Item')], max_length=30),
        ),
    ]
