# Generated by Django 2.1.5 on 2021-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210627_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_long',
            field=models.BooleanField(default=False),
        ),
    ]
