# Generated by Django 2.1.5 on 2021-06-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
