# Generated by Django 2.1.5 on 2021-07-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210704_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='content',
            new_name='tag_name',
        ),
    ]
