# Generated by Django 2.1.5 on 2021-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210704_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='field_ptr',
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Field'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
