# Generated by Django 2.1.5 on 2021-07-04 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210704_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
