# Generated by Django 2.1.5 on 2021-07-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210704_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='field_ptr',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
